services:
  goserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - path: ./.env
        required: true
    ports:
      - "587:587"  # For sending emails
    environment:
      - GIN_MODE=release
  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    ports:
      - "443:8080"  # Server
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
  watchtower:
    image: containrrr/watchtower:armhf-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock