version: '3'
services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "25:25"  # Map port 80 of the container to port 8080 on localhost
    environment:
      - GIN_MODE=release