name: promptus-imperii/build-and-test
on: [push]
jobs:
  does-project-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: 'Compiling the program'
        run: go build .
  does-project-pass-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: 'Running the tests'
        run: go test .